### ISSUE TITLE
use a clearer name for `bao hash --encoded`

### ISSUE THREAD

**Issue by oconnor663** [oconnor663/bao#25]
In https://github.com/oconnor663/bao/issues/24, we discussed a bit how users might imagine that `bao hash --encoded` validates more than it really does. That might not be a big issue if they then go on to do a full `decode` (which validates everything), but still it could worth reconsidering the name to make it clear what it's actually doing. Maybe we could call the command `bao hash --encoded-root` or something like that.

**Comment by oconnor663** [comment]
@casey let me know if you have suggestions here.

**Comment by casey** [comment]
One idea is to make command do the safe, slow thing by default, but allow the user to request the faster, possibly riskier thing.

For example:

`bao hash --encoded` – Validate the root hash, all interior nodes, and all leaf nodes, printing the hash of the root if everything was correct, and printing an error message and returning an error code if anything went wrong.

`bao hash --encoded --root-only` – Only validate the length and the root hash. Bad interior nodes or leaf data is not checked.

Another idea is to create a separate sub-command which returns information about an encoded file:

```
$ bao info $FILE
root hash: 4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b
length: 4097
chunks: 2
depth: 2
```

Which you could then restrict to a particular piece of info:

```
$ bao info --root-hash $FILE
4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b
```

The `bao info` approach might be nice because there is potentially a lot of interesting information about a bao encoded file, and it the command could be extended as needed to print that information.

To make it really hard to misuse, the command could be given a scary name, like `bao unverified-info`. This is kind of ugly though, so I might not do it just on aesthetic grounds :P
