### ISSUE TITLE
Variable node offset defeats chunk-level deduplication

### ISSUE THREAD

**Issue by casey** [oconnor663/bao#29]
I've been thinking about using bao for synchronizing files across a network, and I somewhat belatedly realized that since the node offset is different for each chunk, the same chunk in different positions in the same tree, and the same chunk in different trees will hash to different values.

I definitely understand the rationale for doing so, i.e. to prevent implementors from making non-constant-time optimizations.

However, I think it has a few negative implications in contexts where bao might otherwise be a natural fit. All of these are contexts where constant-time optimizations are permitted, so admittedly not bao's intended use case:

- Simple chunk-level and subtree-level storage deduplication: If chunk hashes are not constant, then a simple chunk deduplication scheme will be defeated. Chunk-level deduplication is used in systems like ZFS, and in piece storage engines for BitTorrent.

- Prepending content to a file: This is somewhat theoretical, but if you wanted to prepend a sequence of chunks to a file, all previously calculated chunk hashes would have to be recalculated, since the node offsets would change.

- Parallel hashing schemes that share only chunks: It seems that this would somewhat complicate parallel hashing schemes by requiring that they communicate the node offset for sequences of chunks, instead of just the chunks themselves.

- Sparse file hashing: This is exactly the thing that including the node offset is intended to prevent, but I think it's worth mentioning anyways. Sparse files are common in a lot of contexts, like pre-allocating a file on disk which will later be filled with data. Although this is exactly the optimization that node offsets are intended to prevent, it is a legitimate optimization in a number of reasonable contexts.

My personal take is that there are compelling reasons to keep chunk hashes constant. The one that seems most important to me is allowing chunk-level deduplication, which will be relevant in the context of file sync over the network.

I also suspect that the optimization that constant chunk hashes permits is so egregious (i.e. `if chunk.iter().all(|b| == 0) { ZEROHASH } else { hash(chunk) }`) that any implementation that uses it is either doing so intentionally, or has other problems that would prevent it from being a constant time implementation.

**Comment by oconnor663** [comment]
The original Bao design did not set the node offset parameter, for exactly the reasons you mentioned. It was @zooko who originally convinced me to switch. You may have read some of his remarks in that other thread: https://github.com/oconnor663/bao/issues/21

My original objection was that the "optimization" was tricky to do, or that it would have big performance downsides in the general case. But when I tried it, I found that it was trivial, and that it had essentially no performance downside. So I changed my mind :)

Some off-the-cuff reactions to specific points:

> Simple chunk-level and subtree-level storage deduplication

A chunk deduplication system would need to distinguish between the hash of the chunk (unique), and the CV of the chunk in a larger file (potentially different for each file). That's not as elegant, since it involves some repeat work, but is it a problem in practice?

> Sparse file hashing

I think the most common case of this is something like maintaining the hash of a disk image. If so, one way to make it still work is to treat the image like a growing file, rather than like a file of constant size. This doesn't work if you seek straight to the end of the disk, but do most filesystems in practice concentrate writes near the front?

**Comment by casey** [comment]
> The original Bao design did not set the node offset parameter, for exactly the reasons you mentioned. It was @zooko who convinced me to switch. You may have read some of his remarks in that other thread: #21

Zooko's remarks make sense to me, although I think I read this tweet a suggesting that maybe the optimization shouldn't be recommended/mentioned in the spec/done in the reference implementation, as opposed to changing the spec to make it impossible:

https://twitter.com/zooko/status/1058632511964639232

> A chunk deduplication system would need to distinguish between the hash of the chunk (unique), and the CV of the chunk in a larger file (potentially different for each file). That's not as elegant, since it involves some repeat work, but is it a problem in practice?

I honestly don't know! I agree that the extra hashing probably doesn't matter for systems where the data is local. However, it would make a difference for distributed systems, where you would either have to transmit two hashes per piece to allow deduplication, or you would have to retrieve pieces which would later be deduplicated and discarded later.

> Note that you'd have the same problem, even without the node offset parameter, if you break the input bytes up into anything that isn't a power-of-2 number of chunks, because the subtree structure isn't determined then.

> You also have to contend with the difference between root and non-root CVs. For that last reason in particular, a deduplication system might prefer a custom hash function that does not distinguish the root, which it can get away with because length extensions are not a concern. (Notably, the BEP 30 tree does not distinguish the root.)

Right, that's true. Subtree deduplication would probably be rarer than chunk deduplication, so isn't as important to preserve.

> This doesn't work if you seek straight to the end of the disk, but do most filesystems in practice concentrate writes near the front?

I think it's not uncommon to write into the middle, for example if you're saving retrieved pieces into a file in bittorrent.

**Comment by oconnor663** [comment]
See https://twitter.com/zooko/status/1069676317027823616.

**Comment by casey** [comment]
Ahh, I didn't see that part of the thread.

I guess I still think it's an unfavorable trade off. I would love to see a hash function specifically dedicated to sparsity and deduplication, but I'm not sure if a good one will be forthcoming any time soon.

**Comment by oconnor663** [comment]
As it turns out, we officially announced the BLAKE3 standard yesterday, which evolved out of the Bao tree mode. The current version of Bao is now based on BLAKE3, so this detail about the chunk counter (as BLAKE3 calls it) is kind of written in stone.

This thread has been really helpful though, because it's made me realize that two things are related:

- The chunk counter prevents caching subtrees. (Small security benefit.)
- The root flag means that the hash of a chunk / subtree isn't the same as its CV in a larger tree. (Critical security requirement, to prevent length extensions.)

A sparse file / chunk caching application might want a specialized hash function that disables *both* of those features, because the security issues they address don't matter to that application. It would be pretty easy to take a BLAKE3 implementation and just rip out those parts. But it would be really important that that such a modified hash never gets used in any case where privacy-sensitive hashes get published. That sort of thing is too subtle to solve with just warnings in the documentation; you might want to give it an entirely different name (a "fingerprint function"?), and maybe figure out some API changes that make it harder to use as a general purpose hash?

**Comment by casey** [comment]
Congrats on the release! It must feel awesome that bao turned into BLAKE3!

> That sort of thing is too subtle to solve with just warnings in the documentation; you might want to give it an entirely different name (a "fingerprint function"?), and maybe figure out some API changes that make it harder to use as a general purpose hash?

I think perhaps that would be a step too far. An alternative approach would be to do away with the chunk counter and the final node flag on what would currently be the root hash, and define a new root hash as the hash of the root hash with the final node flag set:

```
  r (with final node flag set)
  |
  z
 / \
x   y
|   |
a   b
```

Identical leaves and subtrees would have consistent hashes, but the function would still be a secure, cryptographic hash function, albeit a somewhat strange one.

**Comment by oconnor663** [comment]
Thank you :)

> the function would still be a secure, cryptographic hash function

As long as you never used the root pre-hash in a context where you should've used the real-hash! In my mind, this is the sort of thing that real world applications and protocols get wrong *constantly*. I think in a widely used standard, it's too much of a risk, though it's a clever idea.
